source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.4.3'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

ruby IO.read('.ruby-version').strip
gem 'rails', '~> 5.2.0'       # Bundle edge Rails instead: gem 'rails', github: 'rails/rails'

# Webserver
gem 'puma', '~> 3.11'            # Use Puma as the app server

# Database, Models, Controllers
gem 'pg', '>= 0.18', '< 2.0'    # Use postgresql as the database for Active Record
gem 'bcrypt', '~> 3.1.7'        # Use ActiveModel has_secure_password
gem 'redis', '~> 3.0'           # Use Redis adapter to run Action Cable in production
gem 'decent_exposure'           # A helper for creating declarative interfaces in controllers
gem 'monetize'                  # A library for converting various objects into Money objects
gem 'friendly_id', '~> 5.1.0'   #

# Authentication
gem 'devise'                    #

# Exception Handling
#gem 'airbrake', '~> 6.1'       #

# Theme
gem 'bootstrap_sb_admin_base_v2'

# CSS, Scss, Sass, Views
gem 'sass-rails', '~> 5.0'      # Use SCSS for stylesheets

# HTML, Haml
gem 'haml-rails'                # templating engine

# JS, jQuery, Coffeescript
gem 'coffee-rails', '~> 4.2'    # Use CoffeeScript for .coffee assets and views
gem 'jbuilder', '~> 2.5'        # Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jquery-rails'              # Use jquery as the JavaScript library
gem 'turbolinks', '~> 5'        # Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'uglifier', '>= 1.3.0'      # Use Uglifier as compressor for JavaScript assets

# Forms, Inputs, Dropdowns
gem 'american_date'
gem 'carrierwave', '~> 1.0'
gem 'datetimepicker-rails', github: 'zpaulovics/datetimepicker-rails', branch: 'master', submodules: true
gem 'jquery-fileupload-rails'
gem 'simple_form'
gem 'tinymce-rails'             # The tinymce-rails gem integrates the TinyMCE editor with the Rails asset pipeline

# Fonts
gem 'glyphicons-rails'

# SEO
gem 'meta-tags'                 # Search Engine Optimization (SEO) plugin
gem 'sitemap_generator'         # SitemapGenerator is the easiest way to generate Sitemaps in Ruby
gem 'acts-as-taggable-on', '~> 4.0' # This plugin was originally based on Acts as Taggable on Steroids

# Tools
gem 'base58'
gem 'awesome_print'             # Pretty print your Ruby objects with style
gem 'builder'
gem 'email_verifier', :git => 'https://github.com/pennyapp/email_verifier.git'
gem 'marco-polo'                # Shows your app name and environment in your console prompt
gem 'phony_rails'               # Helper to validate, display and save phone numbers
gem 'pry'                       #
gem 'stripe'                    # Online Merchant
gem 'whenever', require: false  # Whenever is a Ruby gem that provides a clear syntax for writing and deploying cron jobs
gem 'yomu'
gem 'rxsd'

# Tracking
gem 'ahoy_matey'                # Ahoy provides a solid foundation to track visits and events
gem 'ahoy_email'                # Simple, powerful email tracking for Rails

# OCR Libs
#gem 'ocr'
gem 'ocr_space'
#gem 'tesseract-ocr'

# Sidekiq
#gem 'sidekiq-spy'              # Sidekiq monitoring in the console. A bit like Sidekiq::Web. But without the web
#gem 'sidekiq_monitor'          # Advanced monitoring for Sidekiq
gem 'sidekiq'                   # Simple, efficient background processing for Ruby
gem 'sidekiq-cron', '0.6.3'     # cron background jobs
gem 'sidekiq-failures'          # Keeps track of Sidekiq failed jobs and adds a tab to the Web UI to let you browse them

# Geo-Coding, Maps, Etc
gem 'googlestaticmap'
gem 'geocoder'                  # geocoding (by street or IP address), reverse geocoding (finding street address based on given coordinates), and distance queries

# Domain Lookup
gem 'whois', '~> 4.0'           # WHOIS client
gem 'whois-parser'              # WHOIS parser

# REST & Parsing Tools
gem 'faraday'                   # Simple, but flexible HTTP client library, with support for multiple backends
gem 'hashie'                    # Hashie is a collection of classes and mixins that make hashes more powerful
gem 'httparty'                  # Makes http fun again!
gem 'mechanize'                 #
gem 'multi_json'                #
gem 'net-http-persistent', '~> 2.9.4'
gem 'nokogiri'                  #
gem 'nori'                      #
gem 'rest-client'               # A simple HTTP and REST client for Ruby
gem 'xml-simple'                # A simple API for XML processing
gem 'rets'                      # A pure-ruby library for fetching data from RETS servers

# Thirparty Data Sources
gem 'rubillow'                  # Rubillow is a ruby library to access the Zillow API
gem 'phone_number_validation'   # Ruby Library for the numverify API
gem 'white_pages'               #
gem 'koala'                     # Koala is a Facebook library for Ruby, supporting the Graph API
gem 'echelon'                   # Theme Park data
gem 'twilio-ruby', '~> 5.6.0'   # Twilio


gem 'rails_admin', '~> 1.2'

group :development, :test do
  gem 'railroady'
  gem 'byebug', platform: :mri    # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'factory_bot_rails'        # Fixtures replacement with a straightforward definition syntax
end

group :development do
  gem 'better_errors'             # Better error page for Rack apps
  gem 'binding_of_caller'         # Retrieve the binding of a method's caller
  gem 'letter_opener'             # Preview mail in the browser instead of sending.
  gem 'web-console', '>= 3.3.0'   # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'listen', '~> 3.1.5'        #
  gem 'spring'                    # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'foreman'                   #
  gem 'annotate'                  # Comment summarizing the current schema
end
